name: Deploy

on:
  release:
    types: [created]


jobs:
  pack_deploy:
    name: Build and deploy DataLake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Build Lambda package
      run: |
        sh scripts/build_lambda_package.sh
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIAR3EUNZTZWXZ2VWWL }}
        aws-secret-access-key: ${{ secrets.zI4p7I8bBUGgiqbL6FvJTowW0d3rlXN2ZduIdZAS }}
        aws-region: us-east-1

    - name: IaC Apply
      env:
        COMMAND_IAC: terraform #terraform/terragrunt
      run: |
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
        $COMMAND_IAC apply -auto-approve

#